"""
list display driver properties for SSD1322 driver

>>> %Run -c $EDITOR_CONTENT

MPY: soft reboot
__class__
__init__
__module__
__name__
__qualname__
clear
__bases__
__dict__
reset
sleep
ENABLE_GRAY_SCALE_TABLE
SET_COLUMN_ADDRESS
WRITE_RAM
READ_RAM
SET_ROW_ADDRESS
SET_REMAP_DUAL_COM_LINE_MODE
SET_DISPLAY_START_LINE
SET_DISPLAY_OFFSET
SET_DISPLAY_MODE_ALL_OFF
SET_DISPLAY_MODE_ALL_ON
SET_DISPLAY_MODE_NORMAL
SET_DISPLAY_MODE_INVERSE
PARTIAL_DISPLAY_ENABLE
PARTIAL_DISPLAY_DISABLE
SET_FUNCTION_SELECTION
DISPLAY_SLEEP_ON
DISPLAY_SLEEP_OFF
SET_PHASE_LENGTH
SET_FRONT_CLOCK_DIVIDER
DISPLAY_ENHANCEMENT_A
SET_GPIO
SET_SECOND_PRECHARGE_PERIOD
SET_GRAY_SCALE_TABLE
SELECT_DEFAULT_LINEAR_GRAY_SCALE_TABLE
SET_PRECHARGE_VOLTAGE
SET_VCOMH_VOLTAGE
SET_CONTRAST_CURRENT
MASTER_CURRENT_CONTROL
SET_MULTIPLEX_RATIO
DISPLAY_ENHANCEMENT_B
SET_COMMAND_LOCK
ENABLE_EXTERNAL_VSL
ENABLE_INTERNAL_VSL
NORMAL_GRAYSCALE_QUALITY
ENHANCED_LOW_GRAY_SCALE_QUALITY
RESERVED_ENHANCEMENT
NORMAL_ENHANCEMENT
COMMANDS_LOCK
COMMANDS_UNLOCK
COLUMN_ADDRESS
ROW_ADDRESS
clear_buffers
write_cmd
present
cleanup
draw_bitmap_GS4
draw_bitmap_mono
draw_bitmap_raw
draw_circle
draw_pixel
draw_ellipse
draw_hline
is_off_grid
draw_letter
draw_line
draw_vline
draw_lines
draw_polygon
draw_rectangle
draw_sprite
draw_text
fill_rectangle
draw_text8x8
fill_circle
fill_ellipse
fill_polygon
load_sprite
set_address
write_data
set_column_address
set_row_address
set_display_enhancement_a
set_display_enhancement_b
wake
>>> 
"""
from ssd1322 import Display
methods = dir(Display)
for method in methods:
    print(method)

